name: MSBuild

on:
  push:
    branches: [ main ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions: write-all

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - run: mkdir build

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}/build
      run: |
        cmake ..
        cmake --build . --config ${{env.BUILD_CONFIGURATION}}
      
    - name: Zip
      uses: vimtor/action-zip@v1
      with:
        files: build/bin/Release/ build/bin/Shipworks.json
        recursive: false
        dest: Artifacts.zip
        
    - name: Upload
      uses: actions/upload-artifact@v3.1.0
      with:
        name: Artifacts
        path: |
          build/bin/Release/
          build/bin/Shipworks.json
        
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v0.1.14
      with:
        files: Artifacts.zip