name: MSBuild

on:
  push:
    branches: [ main ]

env:
  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions: write-all

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: MakeDirs
      run: |
        mkdir build
        mkdir temp

    - name: Build
      run: |
        cmake -S . -B build/
        cmake --build build/ --config ${{env.BUILD_CONFIGURATION}}

    - name: MoveToTemp
      run: |
        mv build/bin/Release/* temp/
        mkdir temp/Modloader
        mkdir temp/Modloader/config
        mkdir temp/Modloader/mods
      
    - name: Upload
      uses: actions/upload-artifact@v3.1.0
      with:
        name: Artifacts
        path: temp/*

    - name: Zip
      uses: vimtor/action-zip@v1
      with:
        files: temp/
        recursive: true
        dest: Artifacts.zip
      if: startsWith(github.ref, 'refs/tags/')
        
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v0.1.14
      with:
        files: Artifacts.zip